# Generated by Django 5.2.1 on 2025-06-01 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('katalog', '0002_alter_product_options_alter_product_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='available',
            field=models.BooleanField(default=True, verbose_name='Доступен'),
        ),
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(default=0, max_length=1500, verbose_name='Описание'),
            preserve_default=False,
        ),
    ]
