# Generated by Django 5.2.1 on 2025-06-05 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('katalog', '0008_order_customer_name_alter_order_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='privacy_policy_accepted',
            field=models.BooleanField(default=False, verbose_name='Согласие на обработку данных'),
        ),
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.TextField(blank=True, null=True, verbose_name='Адрес доставки'),
        ),
        migrations.AlterField(
            model_name='order',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email'),
        ),
    ]
